In [2]:
import pandas as pd

In [3]:
"""
Loads in raw score file
Expecting the schema 
Name	Date	GF	GA	Team

Calcuates result, margies and goal difference
Does some prep work for Form and Win

Obviously names need to be consistant
"""

raw_data = pd.read_csv("../data/results_v2.csv")
raw_data["GD"] = raw_data["GF"] - raw_data["GA"]
raw_data.loc[(raw_data['GD'] == 0), 'GamePoints'] = 0.5
raw_data.loc[(raw_data['GD'] < 0), 'GamePoints'] = -1
raw_data.loc[(raw_data['GD'] > 0), 'GamePoints'] = 1
raw_data.loc[(raw_data['GD'] > 6), 'GamePoints'] = 1.5
raw_data.loc[(raw_data['GD'] < -6), 'GamePoints'] = -1.5
raw_data.loc[(raw_data['GamePoints'] >= 1), 'W'] = 1
raw_data.loc[(raw_data['GamePoints'] == 0.5), 'D'] = 1
raw_data.loc[(raw_data['GamePoints'] <= -1), 'L'] = 1
raw_data.loc[(raw_data['GamePoints'] == 1.5), 'MW'] = 1
raw_data.loc[(raw_data['GamePoints'] == -1.5), 'ML'] = 1

raw_data.loc[(raw_data['GamePoints'] >= 1), 'Result'] = '🔼'
raw_data.loc[(raw_data['GamePoints'] == 0.5), 'Result'] = '➖'
raw_data.loc[(raw_data['GamePoints'] <= -1), 'Result'] = '🔽'
raw_data.loc[(raw_data['GamePoints'] == 1.5), 'Result'] = '⏫'
raw_data.loc[(raw_data['GamePoints'] == -1.5), 'Result'] = '⏬'

raw_data = raw_data[raw_data["Name"].str.contains("\*")==False] # Removes Ringers

raw_data = raw_data.fillna(0)
pd.set_option('display.float_format', '{:.1f}'.format)
raw_data = raw_data.astype({'W':'int','D':'int','L':'int','MW':'int','ML':'int'})

raw_data['Date'] = pd.to_datetime(raw_data['Date'],dayfirst = True)
gameweek_int = raw_data.nunique().Date
gameweek = "Gameweek " + str(gameweek_int)

#display(raw_data)

In [4]:
"""
Creates the Form Column
"""
def form_column(raw_data):
    raw_data['game_rank'] = raw_data.sort_values("Date").groupby("Name").Date.rank(ascending=False)
    raw_data_form = raw_data.loc[raw_data['game_rank'] <= 5]
    form = raw_data_form.groupby(['Name'], as_index=False).agg({'Result': ' '.join})
    return form

form = form_column(raw_data)

#display(form)

In [5]:
"""
Creates Matches Played (MP), Partipation (Par%), Pts and Win% (W%)

It also aggreates all the raw data to create an up to date table
"""
def get_totals(raw_data):
    played = raw_data.groupby('Name').count()
    played = pd.DataFrame(played["Date"]).rename(columns={"Date":"MP"})
    data = raw_data.groupby('Name').sum(numeric_only=True).sort_values(by=['GamePoints'],ascending=False).join(played).rename(columns={"GamePoints":"Pts"})

    data["Par%"] = data["MP"].div(gameweek_int)*100
    data["W%"] = data["W"]/data["MP"]*100
    data = data.astype({'Par%':'int','W%':'int'})
    return data

totals = get_totals(raw_data)



#display(data)

In [7]:
"""
Join tables 
Drops unwanted columns 
Puts columns in the correct order
"""
table = totals.merge(form,on='Name').rename(columns={"Result":"Form"})
table.index = table.Name
table = table[['MP', 'W', 'D', 'L','MW', 'ML', 'GF', 'GA','GD','Par%','W%','Pts','Form']]
table.index.names = [gameweek]
table

             MP  W  D  L  MW  ML   GF   GA  GD  Par%   W%  Pts       Form
Gameweek 11
Calz          7  5  0  2   3   0  117   83  34    63   71  4.5  🔼 🔼 ⏫ 🔽 ⏫
Virlo         3  3  0  0   2   0   57   36  21    27  100  4.0      ⏫ ⏫ 🔼
Wilf          8  6  0  2   2   2  123  113  10    72   75  4.0  🔼 🔼 ⏬ 🔼 ⏬
Schurrle      6  4  0  2   2   1  100   90  10    54   66  2.5  ⏫ 🔼 ⏫ ⏬ 🔽
Zola          3  2  0  1   1   0   47   41   6    27   66  1.5      ⏫ 🔼 🔽
Keysey        3  2  0  1   0   0   47   43   4    27   66  1.0      🔼 🔽 🔼
Doug          6  3  0  3   2   1   87   79   8    54   50  0.5  🔽 ⏫ 🔼 ⏬ 🔽
Peggy         3  1  0  2   0   0   44   47  -3    27   33 -1.0      🔽 🔽 🔼
Gilet         7  3  0  4   1   2  105  116 -11    63   42 -1.5  ⏫ 🔽 ⏬ 🔼 🔽
Mate         10  4  0  6   2   2  150  146   4    90   40 -2.0  🔽 ⏫ ⏫ 🔽 🔼
Helmet        8  3  0  5   1   2  114  130 -16    72   37 -2.5  ⏬ 🔽 ⏫ 🔼 🔼
Reaper       11  5  0  6   0   4  147  175 -28   100   45 -3.0  ⏬ 🔼 ⏬ 🔼 🔽
Kim          10  3  0  7   2   1  140  151 -11    90   30 -3.5  🔼 ⏫ 🔽 🔽 🔽
Noel         10  3  0  7   1   3  128  161 -33    90   30 -5.0  ⏬ 🔽 ⏫ 🔽 🔼

In [24]:
"""
TO DO

Add Graphics
Tracking player pairings
Tracking week by week table position

"""

'\nTO DO\n\nAdd Graphics\nTracking player pairings\nTracking week by week table position\n\n'

In [25]:
display(raw_data)

,Name,Date,GF,GA,Team,GD,GamePoints,W,D,L,MW,ML,Result,game_rank
0,Calz,2023-03-02,16,17,DARKS,-1,-1.0,0,0,1,0,0,🔽,7.0
1,Helmet,2023-03-02,16,17,DARKS,-1,-1.0,0,0,1,0,0,🔽,7.0
2,Kim,2023-03-02,16,17,DARKS,-1,-1.0,0,0,1,0,0,🔽,9.0
3,Mate,2023-03-02,16,17,DARKS,-1,-1.0,0,0,1,0,0,🔽,9.0
4,Peggy,2023-03-02,16,17,DARKS,-1,-1.0,0,0,1,0,0,🔽,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Peggy,2023-05-04,16,13,BLANCOS,3,1.0,1,0,0,0,0,🔼,1.0
96,Zola,2023-05-04,16,13,BLANCOS,3,1.0,1,0,0,0,0,🔼,1.0
97,Reaper,2023-05-04,16,13,BLANCOS,3,1.0,1,0,0,0,0,🔼,1.0
98,Helmet,2023-05-04,16,13,BLANCOS,3,1.0,1,0,0,0,0,🔼,1.0
99,Virlo,2023-05-04,16,13,BLANCOS,3,1.0,1,0,0,0,0,🔼,1.0

In [26]:
def count_same_team(df, name_col, date_col, team_col):
    count = 0
    for idx, row in df.iterrows():
        name = row[name_col]
        date = row[date_col]
        team = row[team_col]
        same_team_df = df[(df[team_col] == team) & (df[date_col] == date)]
        same_team_names = same_team_df[name_col].unique()
        if len(same_team_names) > 1 and name in same_team_names:
            print(same_team_names)
    return count

In [27]:
count_same_team(raw_data, 'Name', 'Date', 'Team')

['Calz' 'Helmet' 'Kim' 'Mate' 'Peggy']
['Calz' 'Helmet' 'Kim' 'Mate' 'Peggy']
['Calz' 'Helmet' 'Kim' 'Mate' 'Peggy']
['Calz' 'Helmet' 'Kim' 'Mate' 'Peggy']
['Calz' 'Helmet' 'Kim' 'Mate' 'Peggy']
['Gilet' 'Reaper' 'Schurrle' 'Keysey' 'Wilf']
['Gilet' 'Reaper' 'Schurrle' 'Keysey' 'Wilf']
['Gilet' 'Reaper' 'Schurrle' 'Keysey' 'Wilf']
['Gilet' 'Reaper' 'Schurrle' 'Keysey' 'Wilf']
['Gilet' 'Reaper' 'Schurrle' 'Keysey' 'Wilf']
['Gilet' 'Helmet' 'Mate' 'Noel' 'Reaper']
['Gilet' 'Helmet' 'Mate' 'Noel' 'Reaper']
['Gilet' 'Helmet' 'Mate' 'Noel' 'Reaper']
['Gilet' 'Helmet' 'Mate' 'Noel' 'Reaper']
['Gilet' 'Helmet' 'Mate' 'Noel' 'Reaper']
['Calz' 'Kim' 'Virlo' 'Wilf' 'Doug']
['Calz' 'Kim' 'Virlo' 'Wilf' 'Doug']
['Calz' 'Kim' 'Virlo' 'Wilf' 'Doug']
['Calz' 'Kim' 'Virlo' 'Wilf' 'Doug']
['Calz' 'Kim' 'Virlo' 'Wilf' 'Doug']
['Gilet' 'Schurrle' 'Virlo' 'Wilf']
['Gilet' 'Schurrle' 'Virlo' 'Wilf']
['Gilet' 'Schurrle' 'Virlo' 'Wilf']
['Gilet' 'Schurrle' 'Virlo' 'Wilf']
['Kim' 'Mate' 'Noel' 'Reaper']
['Kim' 'Mate' 'Noel' 'Reaper']
['Kim' 'Mate' 'Noel' 'Reaper']
['Kim' 'Mate' 'Noel' 'Reaper']
['Mate' 'Noel' 'Kim' 'Doug']
['Mate' 'Noel' 'Kim' 'Doug']
['Mate' 'Noel' 'Kim' 'Doug']
['Mate' 'Noel' 'Kim' 'Doug']
['Calz' 'Reaper' 'Wilf']
['Calz' 'Reaper' 'Wilf']
['Calz' 'Reaper' 'Wilf']
['Kim' 'Noel' 'Peggy' 'Helmet']
['Kim' 'Noel' 'Peggy' 'Helmet']
['Kim' 'Noel' 'Peggy' 'Helmet']
['Kim' 'Noel' 'Peggy' 'Helmet']
['Calz' 'Mate' 'Reaper']
['Calz' 'Mate' 'Reaper']
['Calz' 'Mate' 'Reaper']
['Gilet' 'Mate' 'Reaper']
['Gilet' 'Mate' 'Reaper']
['Gilet' 'Mate' 'Reaper']
['Wilf' 'Noel' 'Kim' 'Schurrle']
['Wilf' 'Noel' 'Kim' 'Schurrle']
['Wilf' 'Noel' 'Kim' 'Schurrle']
['Wilf' 'Noel' 'Kim' 'Schurrle']
['Noel' 'Reaper' 'Gilet' 'Helmet' 'Wilf']
['Noel' 'Reaper' 'Gilet' 'Helmet' 'Wilf']
['Noel' 'Reaper' 'Gilet' 'Helmet' 'Wilf']
['Noel' 'Reaper' 'Gilet' 'Helmet' 'Wilf']
['Noel' 'Reaper' 'Gilet' 'Helmet' 'Wilf']
['Kim' 'Calz' 'Mate' 'Doug' 'Schurrle']
['Kim' 'Calz' 'Mate' 'Doug' 'Schurrle']
['Kim' 'Calz' 'Mate' 'Doug' 'Schurrle']
['Kim' 'Calz' 'Mate' 'Doug' 'Schurrle']
['Kim' 'Calz' 'Mate' 'Doug' 'Schurrle']
['Wilf' 'Gilet' 'Doug' 'Reaper']
['Wilf' 'Gilet' 'Doug' 'Reaper']
['Wilf' 'Gilet' 'Doug' 'Reaper']
['Wilf' 'Gilet' 'Doug' 'Reaper']
['Kim' 'Calz' 'Noel' 'Helmet']
['Kim' 'Calz' 'Noel' 'Helmet']
['Kim' 'Calz' 'Noel' 'Helmet']
['Kim' 'Calz' 'Noel' 'Helmet']
['Calz' 'Zola' 'Noel' 'Mate' 'Helmet']
['Calz' 'Zola' 'Noel' 'Mate' 'Helmet']
['Calz' 'Zola' 'Noel' 'Mate' 'Helmet']
['Calz' 'Zola' 'Noel' 'Mate' 'Helmet']
['Calz' 'Zola' 'Noel' 'Mate' 'Helmet']
['Wilf' 'Reaper' 'Doug' 'Schurrle']
['Wilf' 'Reaper' 'Doug' 'Schurrle']
['Wilf' 'Reaper' 'Doug' 'Schurrle']
['Wilf' 'Reaper' 'Doug' 'Schurrle']
['Noel' 'Kim' 'Mate' 'Gilet' 'Keysey']
['Noel' 'Kim' 'Mate' 'Gilet' 'Keysey']
['Noel' 'Kim' 'Mate' 'Gilet' 'Keysey']
['Noel' 'Kim' 'Mate' 'Gilet' 'Keysey']
['Noel' 'Kim' 'Mate' 'Gilet' 'Keysey']
['Peggy' 'Zola' 'Reaper' 'Helmet' 'Virlo']
['Peggy' 'Zola' 'Reaper' 'Helmet' 'Virlo']
['Peggy' 'Zola' 'Reaper' 'Helmet' 'Virlo']
['Peggy' 'Zola' 'Reaper' 'Helmet' 'Virlo']
['Peggy' 'Zola' 'Reaper' 'Helmet' 'Virlo']

0